FROM node:20-alpine AS base

FROM base AS deps

WORKDIR /app

COPY package.json ./
RUN yarn install --silent

FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN yarn global add vite

EXPOSE 5173

CMD [ "yarn", "run", "dev"]
